### ISSUE TITLE
MCTS and really bad moves

### ISSUE THREAD

**Issue by david-pfx** [jbradberry/mcts#1]
Does your MCTS implementation sometimes play really bad moves? I've written an implementation based on your article, and (testing on TTT) it usually plays well but occasionally fails to play an immediate win or block an immediate loss. Is that your experience, of have you found a way to avoid that happening?

See http://polygame.org (no code project yet).

**Comment by jbradberry** [comment]
@david-pfx I rarely find that it makes truly bad moves unless the game is effectively already lost and all of the moves available have a low simulated win rate.  I can't think of a situation at all where I've seen it fail to take an immediate win, and would consider that a bug since it should have a 100% win rate, making it come out ahead of any other moves no matter how attractive.
